### PR TITLE
Async for each handling

### PR DESCRIPTION
**Pull request by wcrooy**
This PR contains the possibility to handle multiple records at the same time. Based on mem-usage the degree of parallelism can be set. 

Let me know if you've got any further questions or remarks.

### CODE REVIEW

**Comment by Kralizek** [comment]
Hey @wcrooy! 

Thank you for your PR. It's a really nice addition. I wonder whether these extensions should be in a side-package that can be added on the side. What do you think?

**Comment by wcrooy** [comment]
> Hey @wcrooy!
> 
> Thank you for your PR. It's a really nice addition. I wonder whether these extensions should be in a side-package that can be added on the side. What do you think?

Hi @Kralizek. 
You're welcome. I'm ok with both options. Though I think it's pretty close to the _standard_ sqs / sns packages. Since it offers the user two flavours of initialize the processing of messages and notifications.

**Comment by wcrooy** [comment]
Hi @Kralizek , 
Is there anything I can do in assisting to get this PR through? Please let me know your thoughts. 

Regards, Wouter

**Comment by Kralizek** [comment]
Hi @wcrooy, sorry. just busy these days. Is it urgent for you?

**Comment by wcrooy** [comment]
Hi,

No problem! Thanks for even looking at it. 😊 Urgency is medium…

**Comment by Kralizek** [comment]
I'll try to work on it sometimes today. It generally looks really good.

**Comment by Kralizek** [comment]
@wcrooy do you think it's a correct assumption to say that if `maxDegreeOfParallelism == 1` then we're basically running the sync version!

If so, we could merge the two extensions into one.

```csharp
public static IServiceCollection UseNotificationHandler<TNotification, THandler>(this IServiceCollection services, int maxDegreeOfParallelism = 1)
    where TNotification : class
    where THandler : class, INotificationHandler<TNotification>
{
    if (maxDegreeOfParallelism <= 0)
    {
        throw new ArgumentOutOfRangeException(nameof(maxDegreeOfParallelism), $"{nameof(maxDegreeOfParallelism)} can't be less than 1");
    }

    if (maxDegreeOfParallelism > 1)
    {
        services.AddSingleton(new ForEachAsyncHandlingOption { MaxDegreeOfParallelism = maxDegreeOfParallelism });
        services.AddTransient<IEventHandler<SNSEvent>, SnsForEachAsyncEventHandler<TNotification>>();
    }
    else
    {
        services.AddTransient<IEventHandler<SNSEvent>, SnsEventHandler<TNotification>>();
    }

    services.AddTransient<INotificationHandler<TNotification>, THandler>();

    return services;
}
```

**Comment by Kralizek** [comment]
@wcrooy please review the changes I introduced in the latest commit. I think it makes a clearer API.

This is the idea:

```csharp
// Non-parallel execution (implicit)
services.UseNotificationHandler<CustomNotification, CustomNotificationHandler>();

// Non-parallel execution (explicit)
services.UseNotificationHandler<CustomNotification, CustomNotificationHandler>(enableParallelExecution: false);

// Parallel execution, max parallelism set to available CPU count
services.UseNotificationHandler<CustomNotification, CustomNotificationHandler>(enableParallelExecution: true);

// Parallel execution, max parallelism set to specific value
services.ConfigureSnsParallelExecution(4);
services.UseNotificationHandler<CustomNotification, CustomNotificationHandler>(enableParallelExecution: true);
```

Similarly for SQS.

**Review by wcrooy — COMMENTED** [review]
Yes! Thanks! I like them. :-)

**Review by Kralizek — APPROVED** [review]

**Pull request merged**
