### PR TITLE
Add SQS support

### PR DESCRIPTION
**Pull request by derwasp**
- Added Sqs template
- Removed x86\x64 configurations

### CODE REVIEW

**Comment by Kralizek** [comment]
hey @derwasp !

Thanks for your PR! I will check it ASAP.
Since I'm in a kind of busy period, do you have an immediate need for a released package?

**Comment by derwasp** [comment]
Awesome, thanks!
It's basically a copy-paste of the SNS package with a rename and small adjustments.
I already have it in the project which I am aiming on using, so can survive without the package for the time being ;) It's just I though that if I already have it there, why not just put it here.

**Comment by Kralizek** [comment]
Hey! Would you mind adding the template for the SQS function?

You can see the equivalent for SNS here: https://github.com/Kralizek/AWSLambdaSharpTemplate/tree/master/templates/content/SnsEventFunction

**Comment by derwasp** [comment]
@Kralizek I will try looking into it in the coming few days. Just have some other stuff atm.

**Comment by Kralizek** [comment]
@derwasp I apreciate a lot! :)

**Comment by derwasp** [comment]
Can you see if the template looks okay?
It don't think it will work, though. Because the sqs package is not available. So if you were to publish this, you'll have to change the Sqs package dependency in the template.

**Comment by Kralizek** [comment]
@derwasp good point! thanks for adding the template :)

I'll give a look at it this weekend :)

**Review by Kralizek — CHANGES_REQUESTED** [review]
I suggested some changes via the PR on your fork. https://github.com/albumprinter/AWSLambdaSharpTemplate/pull/1

**Comment by derwasp** [comment]
Merged! You could have just merged it directly in the branch 👍

**Comment by Kralizek** [comment]
@derwasp I didn't know how to add commits to your PR :(

**Comment by derwasp** [comment]
@Kralizek I haven't done it myself, but github says this:

image

Anyway, we have it merged now. Thank you!

**Comment by derwasp** [comment]
@Kralizek when are you planning on merging the PR?

**Comment by Kralizek** [comment]
@derwasp oh shit! sorry! I've been swamped with work this week!

**Comment by derwasp** [comment]
It's okay ;) Just poking as a reminder

**Comment by derwasp** [comment]
@Kralizek ping ;)

**Comment by Kralizek** [comment]
I was unable to push to your branch.
Anyway I added some tests and merged everything into master.
Thanks for your help and sorry If I made you wait too long :)

@derwasp

**Comment by derwasp** [comment]
@Kralizek thank you! Well, I merged the PR you did, so the changes were there.
Everything's cool, sorry for being annoying about it.

**Pull request merged**
