### PR TITLE
Improve customization of service registration

### PR DESCRIPTION
**Pull request by Thomas-X**
The idea for this PR is so you can pass your own serialization logic incase your incoming messages are in an other format than JSON. 

I added unit tests too, but let me know if there's any questions or remarks on how it's structured. README is updated to reflect the (optional) API changes as well

### CODE REVIEW

**Comment by Kralizek** [comment]
Hi @Thomas-X 
Thank you for your pull request. I will be checking the PR thoroughly sometimes this week (hopefully already tomorrow but I can't promise).

In the meantime, I would appreciate if you could revert some codestyle changes that slipped through when you committed your changes.

I'm asking this because it makes it easier to understand what was changed in the PR.

**Comment by Thomas-X** [comment]
Changed some of the formatting that slipped through, maybe it could be worth adding a [.editorconfig](https://editorconfig.org/) for the future

**Comment by Kralizek** [comment]
Hi @Thomas-X, sorry for the delay.

I have been thinking a bit about this PR and I think that adding (yet) another parameter to the registration methods is not sustainable in the long term.

I'm considering the idea of using a configuration delegate that can be used to customize the registered services as needed.

Something like below

```csharp
services.UseNotificationHandler(c => c.UseSerializer<MyCustomSerializer>().EnableParallelExecution());
```

So my plan is to rewrite this PR with this design but I am not sure when I have time to do so.

**Comment by Thomas-X** [comment]
Hi @Kralizek, no problem, we all have lives :).

I think that using a configuration delegate definitely makes it more future-proof and more extensible, so we should rewrite this PR for that. 

I'm a bit dry on time as well, but I can take a look at the idea next week(end) probably, and see if I'm able to implement it! (I'm a junior dev). Unless you beat me to the punch, of course

**Comment by Kralizek** [comment]
@Thomas-X managed to squeeze a nick of time for the lib part. tests need to be updated as the build is failing now.

**Comment by Thomas-X** [comment]
@Kralizek That's really awesome, I'll see what I can do soon to get it built and the tests green

**Comment by Kralizek** [comment]
Could you add an implementation of `ISerializer` for JSON so that we skip that ugly `if`?

**Comment by Kralizek** [comment]
Left to do before merge:
- [ ] Update readme

Left to do before new release:
- [ ] Update CI/CD #18 
- [ ] (optional) Convert unit tests to use AutoFixture and Moq #19

**Comment by Kralizek** [comment]
Hey @Thomas-X I was working on this lib and by mistake I fucked up your PR while rebasing it after I merged in #22 

I am not able to reopen this PR. I have the code locally but I'd love if you would open a new PR so that you can take credit on the work you did.

Best regards and sorry =)

**Pull request closed without merging**
